name: GitHub Release
on:
  workflow_dispatch:
    inputs:
      label:
        description: Label to determine verion segment to increment.
        type: string
        default: patch

  pull_request_target:
    types: [ closed ]
    branches:
      - dev
jobs:
  release:
    name: Bump the version number, tag, and release.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Require a label and version bump to package and release
        uses: mheap/github-action-required-labels@v2
        with:
          mode: minium
          count: 1
          labels: "dev, alpha, beta, rc"
      - uses: actions/checkout@v3
        with:
           persist-credentials: true
      - uses: ksuderman/github-action-bump-version@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: abm/VERSION
          parser: cat
          type: ${{ label }}
      - uses: ksuderman/github-action-tag-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: abm/VERSION
          parser: cat
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install pypa/build
        run: python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/